version: '3.7'
services:

  #Bluesky App
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: gex_dev/laravel
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - mynet

#Nginx Service
  nginx:
    build:
      context: ./
      dockerfile: ./nginx2/Dockerfile
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8888:80"
      - "444:444"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - mynet

#MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: blueskydb
      MYSQL_USER: bluesky
      MYSQL_PASSWORD: fr33d0m
      MYSQL_ROOT_PASSWORD: F0rfr33d0m
    volumes:
      - mysqldata:/var/lib/mysql/
    networks:
      - mynet

#phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: bluesky
      PMA_PASSWORD: fr33d0m
    ports:
      - "8082:80"
    networks:
      - mynet


#Docker Networks
networks:
  mynet:
    driver: bridge
#Volumes
volumes:
  mysqldata:
    driver: local
